<?php

/**
 * @file
 * Helper module for the entity_embed tests.
 */

/**
 * Implements hook_entity_embed_context_alter().
 */
function entity_embed_test_entity_embed_context_alter(&$context, $entity) {
  // Allow tests to enable or disable this hook.
  if (!variable_get('entity_embed_test_entity_embed_context_alter', FALSE)) {
    return;
  }

  // Change the view mode to 'teaser'.
  $context['data-entity-embed-settings']['view_mode'] = 'teaser';
}

/**
 * Implements hook_entity_embed_alter().
 */
function entity_embed_test_entity_embed_alter(&$build, $entity, $context) {
  // Allow tests to enable or disable this hook.
  if (!variable_get('entity_embed_test_entity_embed_alter', FALSE)) {
    return;
  }

  // Set title of the 'node' entity.
  $node = $build['node'][$entity->nid]['#node'];
  $node->title = 'Title set by hook_entity_embed_alter';
}
